function zodiac(){
  var birthmonth = document.getElementById("month").value;
   var birthday = document.getElementById("day").value;
 var result = " unknown because you didn't put a valid date.";


if (birthmonth == 1&& birthday >= 20 || birthmonth == 2 && birthday <= 18
    ){
        result = ("Aquarius");
     document.getElementById("photo").innerHTML="<img src='aquarius.png'width=20%>";
   document.getElementById("characteristic").innerHTML="Aquarians are unique, independent and enigmatical. There is no one quite like an Aquarius, and because each is so incredibly individual, it can be tough to describe them as a group. Aquarians don't like labels, and may shy away from any adjective, even the good ones you might bestow upon them. <br><br>Aquarians believe in the nature of change and evolution, and even though they're a fixed sign, they may not necessarily believe they are the same people they were when they were born. Aquarius is intellectual and analytical, but don't mistake these attributes for aloofness. <br><br>Aquarians have deep passion, but they know jumping into something too quickly can cause more harm than good. Aquarians are often big-picture thinkers who can see connections in a way that eludes others. Aquarians have energy, warmth, and a deep desire to get things done.";
  
    }

    if (birthmonth == 2&& birthday >= 19 || birthmonth == 3&& birthday <= 20){
       result = ("Pisces");
       document.getElementById("photo").innerHTML="<img src='pisces.png'width=20%>";
      document.getElementById("characteristic").innerHTML="Smart, creative, and deeply intuitive, Pisces can be close to psychic. Pisces feel things deeply, and have incredibly strong gut reactions. A Pisces knows things from deep within, and can often judge whether a person or situation is good or bad. That doesn't mean a Pisces ignores the logical part of their brain, though. Deeply intelligent, Pisces have a profound respect for the power of the human mind. Is it a surprise that Albert Einstein was a Pisces? <br><br>Pisces signs are sensitive, and get along well in small groups of people. Sometimes, a Pisces may feel like they have an internal and external self, and they may need to spend a lot of time solo to recalibrate those two halves of themselves. A Pisces is rarely lonely when they are by themselves, and have an active imagination. Creative, Pisces love spending time reading, exploring or creating art or music, and understanding their emotions through art.<br><br>A Pisces has a great gut and great intuition, which can guide them well, and help them make creative or intellectual leaps other people might not be able to see or consider. Deeply imaginative, Pisces can happily spend hours daydreaming, and are often just as surprised as the rest of the world when the pieces come together in an amazing way. <br><br>Pisces don't necessarily work the same way as other people do, and they may be able to get things done incredibly quickly. But it's not that they're that much faster than other zodiac signs. It's that the time they may have been caught staring into space are times that are deeply valuable to them, and necessary for any creative process. The more a Pisces understands how they work and respects that process, the better they are.";
      
    }
   if (birthmonth == 3&& birthday >= 21 || birthmonth == 4 && birthday <= 19){
       result = ("Aries");
      document.getElementById("photo").innerHTML="<img src='aries.png'width=20%>";
     document.getElementById("characteristic").innerHTML="Aries will never do something just because everyone else is doing it—a Ram needs to be 100 percent committed to the task at hand. Competitive to the max, the best way to motivate an Aries is to turn something into a contest. Aries will put everything they have (and then some) into winning. Loyal, smart, and impulsive, they always have multiple projects on their mind, and won't be satisfied until their work, social life, and personal lives line up exactly with the dream life they've envisioned. Those who are drawn to magnetic Aries may have trouble keeping up—but if they can, they'll have a friend for life.<br><br>An Aries sign will always tell you what they're thinking, with a frankness that may occasionally border on rudeness. But even if an Aries seems overly blunt with their opinion, that's only because Rams value honesty above all else.<br><br>Whether it's backpacking around the world, launching a business, or training for a marathon, once an Aries sets a goal, they will achieve it. They don't care what anyone else thinks, and can tune into their intuition and dreams in a heartbeat. Rams never need a plus one—they love their own company, and consider going solo to the movies a rare treat.";
   }
  
    if (birthmonth == 4&& birthday >= 20|| birthmonth == 5 && birthday <= 20){
        result = ("Taurus");
       document.getElementById("photo").innerHTML="<img src='taurus.png'width=20%>";
       document.getElementById("characteristic").innerHTML="Smart, ambitious, and trustworthy, Taurus is the anchor of the Zodiac. Amazing friends, colleagues, and partners, Taureans value honesty above all else and are proud that their personal relationships tend to be drama free. Bulls get the reputation of being stubborn, but they're not always stuck in their ways. This searching sign is willing to see another point of view, but they won't flip-flop on an opinion just to make someone else happy. They will shift their thinking only if they truly have a change of heart.<br><br>With a rep as one of the hardest-working signs in the Zodiac, a Bull is never afraid to roll up those sleeves and get to work, and won't blink an eye at pulling an all-nighter to get the job done. But it's not all work for a Taurus sign. Anchored by the earth, this passionate sign is all about sensuality, and is always seeking out pleasure. Whether they're indulging in luxurious massages, spending hours in bed with their lover, or going on a long run, Taureans love feeling present in their body and frequently need to get in touch with their physical self.<br><br>Persistent and hardworking, once a Taurus sets a goal, it will get done—despite any obstacles that may come up. While becoming friends with a Taurus can be tough since they're so particular about who they want in their social circle, once you're in, you're in for life. Taurus doesn't get pulled down by gossip or petty drama. They'll always see the best in their loved ones and buoy them up when they're feeling down";
      
    }
  
    if (birthmonth == 5&& birthday >= 21 || birthmonth == 6 && birthday <= 20
     ){
        result = ("Gemini");
       document.getElementById("photo").innerHTML="<img src='gemini.png'width=20%>";
      document.getElementById("characteristic").innerHTML="Smart, passionate, and dynamic, Gemini is characterized by the Twins, Castor and Pollux, and is known for having two different sides they can display to the world. Expert communicators, Gemini is the chameleon of the Zodiac, adept at blending into different groups based on the vibe and energy they perceive. While they're also amazing at showcasing surface traits, the Gemini well runs deep, which is why the Twins are one of the Zodiac's most emotionally intelligent signs.<br><br>Energetic and quick-witted, Gemini never gets stuck in the past and doesn't ruminate on what might have been. Instead, they move forward with glass-half-full optimism and an ability to always look on the bright side—and land on their feet—in nearly any situation. With a mind that's constantly racing, even when they're just quietly hanging out, the Twins never get bored. In fact, Gemini are happy keeping their own company, and can often turn their solitary daydreams into reality.<br><br>Equipped with almost uncanny emotional intelligence, Gemini can easily read a room and know exactly what other people want to hear from them. They can easily shift their personality depending on mood, going from Friday night life of the party to Monday morning office superstar. Energetic and passionate, Gemini can breathe new life into a same-old routine and excite other people simply by their all-in presence.";
     
    }
  
    if (birthmonth == 6&& birthday >= 21 || birthmonth == 7&& birthday <= 22){
        result = ("Cancer");
       document.getElementById("photo").innerHTML="<img src='cancer.png'width=20%>";
      document.getElementById("characteristic").innerHTML="Emotional, intuitive, and practically psychic; ruled by the moon and characterized by the crab, Cancer has so much going on in its watery depths. Cancer signs may seem prickly and standoffish at first meeting, once they make the decision to become friends with someone, that person has a friend for life.<br><br>Most Cancer signs have been called psychic at some point, and with good reason. Cancer can often intuit relationships, ideas, and motivations before anyone has actually spoken. Hates small talk, especially when it contains white lies (like saying, 'How nice to see you!' when it's clear that both parties would rather avoid each other). That's why social gatherings can be overwhelming for Cancers. They'd much rather spend time in small groups where everyone is on the same page.<br><br>With off-the-charts emotional intelligence, Cancer quickly cuts through the BS and noise to the heart of an issue. Crabs don't need all the facts and figures to know the right course of action, and their ability to trust intuition without judgment can aid them well. This gift is one that other Zodiac signs can learn from and be inspired by.";
      
    }
    if (birthmonth == 7&& birthday >= 23 || birthmonth == 8 && birthday <= 22){
        result = ("Leo");
       document.getElementById("photo").innerHTML="<img src='leo.png'width=20%>";
            document.getElementById("characteristic").innerHTML="Bold, intelligent, warm, and courageous, fire sign Leo is a natural leader of the Zodiac, ready to blaze a trail, vanquish injustice, and make a name for themselves along the way. Blessed with high self-esteem, Lions know that they possess enviable traits—and they're proud of them. They don't believe in false modesty and will be the first to praise themselves for a job well done. But Leo isn't self-aggrandizing or unwilling to roll up those sleeves and do the work: this sign knows that in order to be respected and admired, he or she needs to put in the effort worthy of a leader.<br><br>But it's not all hard work for Lions. Intense and energetic, Leos thrive on social interactions and have no problem making friends—although pinning them down to spend time with you is another story. Leos put themselves first, and will turn down a plan that doesn't fit with their agenda or idea of fun. This trait has gained them an unfair reputation for arrogance. But on the flip side, when a Lion chooses to spend time with you, it's genuinely because he or she wants to.<br><br>A natural leader, Leo's very presence inspires others to be the best they can be. But with great power comes great responsibility. Leos love the pull of the limelight, and they're occasionally swayed by what other people want (or expect) them to do. Although this sign has a loud inner voice, learning to listen to it—especially if it's guiding them toward an unpopular move—is a lifelong lesson that will only make proud Lions stronger and more resilient.";
      
    }
    if (birthmonth == 8 && birthday >= 23 || birthmonth == 9 && birthday <= 22){
        result = ("Virgo");
       document.getElementById("photo").innerHTML="<img src='virgo.png'width=20%>";
        document.getElementById("characteristic").innerHTML="Smart, sophisticated, and kind, Virgo gets the job done without complaining. Virgos are amazing friends, always there to lend a hand and also lend advice. Practical Virgos are incredibly adept at big picture thinking, and planning out their life, their vacations, and what they're going to do today isn't a drag it makes them feel in control and secure.<br><br>Virgo has a rich inner life, and can sometimes seem shy at first meeting. A Virgo won't spill secrets right away, and it's important to earn a Virgo's trust. But once you do, that Virgin will be a friend for life. And if you think that you're dating a shy Virgo, trust that those walls will fall down in the bedroom. One of the most passionate signs, Virgos specialize at connecting to their physicality, and this earth sign loves and celebrates physical connection with their partner.<br><br>Virgos expect perfection from themselves, and they may project those high standards on the other people in their life. A Virgo hates when someone lets him or her down, even if it's minor and unavoidable, like a last-minute cancellation. Virgo signs never want to disappoint the people in their lives, so they may spread themselves too thin put themselves last.<br><br>Graceful, harmonious, and obsessed with making things the very best they can be, Virgo is notorious for being type A but that's only because this sign knows that everything good can be made great, and that everything great can be perfect. Smart and intensely curious, Virgos are passionate about uncovering the why which is why a Virgo's friends consider him or her their own personal encyclopedia. Known for their grace, Virgos can always talk their way out of sticky situations, and everyone is charmed by their wit and ability to put others at ease.";
    }
    if (birthmonth == 9&& birthday >= 23 || birthmonth == 10&& birthday <= 22){
      result = ("Libra");
       document.getElementById("photo").innerHTML="<img src='libra.png'width=20%>";
        document.getElementById("characteristic").innerHTML="Intelligent, kind, and always willing to put others before themselves. Libras value harmony in all forms. Libra adores a life that looks good. As the master of compromise and diplomacy, Libra is adept at seeing all points of view, and excels at crafting compromises and effecting mediation between others. This sign has a rich inner life yet loves other people, and they're always happiest with a large group of friends, family, and coworkers on whom they can count.<br><br>Libras believe that they're directing their own lives, and they take a big-picture approach in making that life look and feel the best it can be. They spend a lot of time figuring out what's missing from that big picture, and they may feel unhappy if they become too focused on one thing, whether it's work, a partner, or a family member. Librans are at their best when they balance their schedule to include plenty of time for self-care rituals and personal pursuits, and when they give themselves enough flexibility to change focus.<br><br>Libra's everyday vibe is this gentle reminder: 'Let's just all get along.' For this sign, compromise is key. Librans don't do well when anyone in their orbit isn't happy, and they're especially adept at inviting other signs to see things from a different perspective. A Libra doesn't strong arm or use coercion, but rather relies on his or her communication prowess to help everyone see another side to a story.";
    }
    if (birthmonth == 10 && birthday >= 23|| birthmonth == 11 && birthday <= 21){
       result = ("Scorpio");
       document.getElementById("photo").innerHTML="<img src='scorpio.png'width=20%>";
        document.getElementById("characteristic").innerHTML="Passionate, independent, and unafraid to blaze their own trail no matter what others think, Scorpio signs make a statement wherever they go. They love debates, aren't afraid of controversy, and won't back down from a debate. They also hate people who aren't genuine, and are all about being authentic—even if authentic isn't pretty.<br><br>Their feelings are what drives them and strengthens them, but their mutability can scare them and make them feel vulnerable and out of control. Because of this conflict, Scorpios, like their namesake, the scorpion, put up an outer shell and may seem prickly. But once people get beyond the shell, they find a loyal, loving person whose passion knows no bounds. Scorpio dives into all life has to offer with 110% enthusiasm. A Scorpio will be your most loyal friend, most dedicated employee—and your worst enemy, if they want to be.<br><br>So many other signs spend valuable time and energy beating around the bush, desperately trying to find an approach that makes the fewest waves when it comes to confronting a conflict. Not Scorpio. Blessed with a deep sense of self, Scorpio is always able to say exactly what's on their mind, even if it's not what people want to hear. Scorpio is forthright and honest, and those two characteristics commandeer a ton of respect, both at home and at work.";
    }
    if (birthmonth == 11 && birthday >= 22 || birthmonth == 12 && birthday <= 21){
        result = ("Sagittarius");
       document.getElementById("photo").innerHTML="<img src='sagittarius.png'width=20%>";
        document.getElementById("characteristic").innerHTML="Independent and strong-willed, Sagittarius personalities are all about going off the beaten path. Sagittarius isn’t afraid to step away from the pack, and is a natural born leader who goes after what he or she wants, regardless of what other people think. Sagittarius is a born adventurer, and loves solo travel and exploration. Sagittarius also loves exploring the inner workings of their minds, and love stretching their horizons through a good book or movie.<br><br>Sagittarius is open-hearted, generous, and big-spirited, but Sagittarius is always truthful. Because of this, they may hurt others’ feelings, or may be called out for not having tact or empathy. The latter is not true. With their keen imagination, Sagittarius is adept at putting themselves in another person’s shoes—that’s why so many Sagittarius are successful actors—but they do not feel the need to beat around the bush or lie. You can trust a Sagittarius to tell you what they really think. You can also trust a Sagittarius, period. Unlike other signs, they won’t spill any secrets.<br><br>Sagittarius is adept at blazing their own paths, and can always go it alone. Sagittarius doesn’t need a roadmap, and can easily conceptualize ideas and opportunities that others may not easily “see.” Sagittarius doesn’t need permission or approval, and has a strong sense of self that allows them to always feel sure-footed, even where others may be unsure or insecure.";
    }
  
  if(birthmonth == 12 && birthday >= 22 || birthmonth == 1 && birthday <= 19){
 
        result = ("Capricorn");
     document.getElementById("photo").innerHTML="<img src='capricorn.png'width=20%>";
     document.getElementById("characteristic").innerHTML="Smart, hardworking, and fully in control of their destiny, Capricorn signs will always get what they set their mind to, in both personal and professional life—no excuses. Capricorns may get a reputation as stubborn, but they simply know what they want, and also know how they wish other people would behave.<br><br>Capricorns love family, and put a lot of stock in traditions. A Capricorn might stress themselves out trying to do everything perfectly—a Capricorn may feel like they must present a home-cooked meal every day, and would never admit to doing drive-thru or takeout. Capricorns believe presentation is everything, and their homes are usually Insta-worthy. A Capricorn sometimes is overly focused on what things look like, instead of how things feel, which could cause them to feel stifled and unhappy.<br><br>Capricorn is intelligent, detail-oriented, and will not take no for an answer when they want something. Their hard working attitude is an inspiration to all, and they truly believe they can achieve anything with hard work. Capricorn is always ready to learn new skills, and sees something they don’t know—like changing a tire or boiling the perfect egg—as a challenge they must undertake. This attitude makes them a master of all trades, and they have esoteric knowledge that is impressive to all who know them.";
    }else if (birthmonth>12||birthday>31){
       alert("Please enter an accurate date ! ");
    }
 document.getElementById("output").innerHTML= result;
}